[vcs]
software = "Git"

[vcs.strict]
mainline = "main"

[modules.root]
main = true
path = "."
packageManager = "Npm"


[modules.tauri]
path = "src-tauri"
packageManager = "Cargo"

[modules.tauri-config]
path = "src-tauri"
packageManager = "Generic"
file = "tauri.conf.json"
format = "json"
versionField = "version"

[modules.root.hooks.after_rel]
build = ["pnpm", "run", "build"]
test = ["pnpm", "run", "test"]
